name: Github Actions Demo

on:
 push:
   branches: [main]
   paths-ignore: [./github/**]
 pull_request:
   branches: [main]
 schedule:
   - cron: '15 6 * * 0'
 workflow_dispatch:
    inputs:
        environment:
        required: true
        type: environment
        description: Select the environment
   
 
jobs:
  build: 
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: output event
        run: echo ${{ github.event_name }}
      - name: output branch
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v3
      - name: list files in repo
        run: tree
